/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssetSplatRouteImport } from './routes/api/asset.$'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files.$'
import { Route as PProjectIndexRouteImport } from './routes/p.$project.index'
import { Route as ApiPageProjectVideoRouteImport } from './routes/api/page.$project.$video'
import { Route as ApiUploadProjectNameRouteImport } from './routes/api/upload.$project.$name'
import { Route as PProjectVVideoRouteImport } from './routes/p.$project.v.$video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetSplatRoute = ApiAssetSplatRouteImport.update({
  id: '/api/asset/$',
  path: '/api/asset/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIndexRoute = PProjectIndexRouteImport.update({
  id: '/p/$project/',
  path: '/p/$project/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPageProjectVideoRoute = ApiPageProjectVideoRouteImport.update({
  id: '/api/page/$project/$video',
  path: '/api/page/$project/$video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadProjectNameRoute = ApiUploadProjectNameRouteImport.update({
  id: '/api/upload/$project/$name',
  path: '/api/upload/$project/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectVVideoRoute = PProjectVVideoRouteImport.update({
  id: '/p/$project/v/$video',
  path: '/p/$project/v/$video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/p/$project/': typeof PProjectIndexRoute
  '/api/page/$project/$video': typeof ApiPageProjectVideoRoute
  '/api/upload/$project/$name': typeof ApiUploadProjectNameRoute
  '/p/$project/v/$video': typeof PProjectVVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/p/$project': typeof PProjectIndexRoute
  '/api/page/$project/$video': typeof ApiPageProjectVideoRoute
  '/api/upload/$project/$name': typeof ApiUploadProjectNameRoute
  '/p/$project/v/$video': typeof PProjectVVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/p/$project/': typeof PProjectIndexRoute
  '/api/page/$project/$video': typeof ApiPageProjectVideoRoute
  '/api/upload/$project/$name': typeof ApiUploadProjectNameRoute
  '/p/$project/v/$video': typeof PProjectVVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/asset/$'
    | '/api/files/$'
    | '/p/$project/'
    | '/api/page/$project/$video'
    | '/api/upload/$project/$name'
    | '/p/$project/v/$video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/asset/$'
    | '/api/files/$'
    | '/p/$project'
    | '/api/page/$project/$video'
    | '/api/upload/$project/$name'
    | '/p/$project/v/$video'
  id:
    | '__root__'
    | '/'
    | '/api/asset/$'
    | '/api/files/$'
    | '/p/$project/'
    | '/api/page/$project/$video'
    | '/api/upload/$project/$name'
    | '/p/$project/v/$video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssetSplatRoute: typeof ApiAssetSplatRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  PProjectIndexRoute: typeof PProjectIndexRoute
  ApiPageProjectVideoRoute: typeof ApiPageProjectVideoRoute
  ApiUploadProjectNameRoute: typeof ApiUploadProjectNameRoute
  PProjectVVideoRoute: typeof PProjectVVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$': {
      id: '/api/asset/$'
      path: '/api/asset/$'
      fullPath: '/api/asset/$'
      preLoaderRoute: typeof ApiAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/': {
      id: '/p/$project/'
      path: '/p/$project'
      fullPath: '/p/$project/'
      preLoaderRoute: typeof PProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/page/$project/$video': {
      id: '/api/page/$project/$video'
      path: '/api/page/$project/$video'
      fullPath: '/api/page/$project/$video'
      preLoaderRoute: typeof ApiPageProjectVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/$project/$name': {
      id: '/api/upload/$project/$name'
      path: '/api/upload/$project/$name'
      fullPath: '/api/upload/$project/$name'
      preLoaderRoute: typeof ApiUploadProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/v/$video': {
      id: '/p/$project/v/$video'
      path: '/p/$project/v/$video'
      fullPath: '/p/$project/v/$video'
      preLoaderRoute: typeof PProjectVVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssetSplatRoute: ApiAssetSplatRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  PProjectIndexRoute: PProjectIndexRoute,
  ApiPageProjectVideoRoute: ApiPageProjectVideoRoute,
  ApiUploadProjectNameRoute: ApiUploadProjectNameRoute,
  PProjectVVideoRoute: PProjectVVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
